source 'https://github.com/CocoaPods/Specs.git'

target 'sputnik-maps-ios-sdk', :exclusive => true do
  pod "sputnik-maps-ios-sdk", :path => "../sputnik-maps-ios-sdk.podspec"
end

target 'Tests', :exclusive => true do
  pod "sputnik-maps-ios-sdk", :path => "../sputnik-maps-ios-sdk.podspec"
end
